[navbar]
logo = "/pfp.png"
items = [
    [
        { name = "My Projects", url = "projects/", md = "projects/index.md" },
        { name = "Blog", url = "blog/", md = "blog/index.md" },
    ],
]
socials = [
    { icon = "github", url = "https://github.com/funnsam" },
    { icon = "discord", url = "https://discord.com/invite/Vwwe7nzH" },
    { icon = "twitter", url = "https://x.com/funnsam1" },
    { icon = "threads", url = "https://www.threads.net/@funn.is_a.dev" },
]
