[navbar]
logo = "/pfp.png"
items = [
    [
        { name = "My Projects", url = "projects/", md = "projects/index.md" },
        { name = "Blog", url = "blog/", md = "blog/index.md" },
    ], [
	    { name = "Github", url = "https://github.com/funnsam" },
    ],
]
